In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('sample_data.csv')
data.head()

   Region   Age    Income Online Shopper
0  Brazil  38.0   83572.0             No
1     USA  26.0  106573.0             No
2  Brazil   NaN       NaN            Yes
3     USA  20.0  107675.0             No
4   India   NaN       NaN             No

In [16]:
X = data.iloc[: , :-1].values

In [19]:
y = data.iloc[: , -1].values

In [21]:
from sklearn.impute import SimpleImputer

In [24]:
si = SimpleImputer(missing_values=np.nan , strategy='mean')
si.fit(X[: , 1:])
X[: , 1:] = si.transform(X[: , 1:])

In [27]:
X

array([['Brazil', 38.0, 83572.0],
       ['USA', 26.0, 106573.0],
       ['Brazil', 42.425, 84411.45],
       ['USA', 20.0, 107675.0],
       ['India', 42.425, 84411.45],
       ['India', 42.425, 84411.45],
       ['Brazil', 42.425, 84411.45],
       ['Brazil', 21.0, 88417.0],
       ['USA', 41.0, 95610.0],
       ['Brazil', 30.0, 93070.0],
       ['Brazil', 42.425, 84411.45],
       ['USA', 42.0, 99195.0],
       ['India', 26.0, 72067.0],
       ['Brazil', 57.0, 52503.0],
       ['USA', 38.0, 111125.0],
       ['USA', 68.0, 113726.0],
       ['USA', 54.0, 67414.0],
       ['USA', 27.0, 66479.0],
       ['Brazil', 46.0, 43105.0],
       ['USA', 42.425, 84411.45],
       ['India', 42.425, 84411.45],
       ['USA', 58.0, 72774.0],
       ['USA', 25.0, 98620.0],
       ['India', 30.0, 43624.0],
       ['USA', 42.425, 84411.45],
       ['India', 36.0, 89203.0],
       ['USA', 42.425, 84411.45],
       ['USA', 58.0, 94680.0],
       ['India', 68.0, 82844.0],
       ['Brazil', 58.0, 118065.0],
       ['Brazil', 56.0, 54920.0],
       ['Brazil', 49.0, 118342.0],
       ['Brazil', 39.0, 61169.0],
       ['USA', 63.0, 51535.0],
       ['Brazil', 69.0, 110862.0],
       ['USA', 42.425, 84411.45],
       ['Brazil', 24.0, 97735.0],
       ['USA', 19.0, 47869.0],
       ['USA', 58.0, 77103.0],
       ['India', 26.0, 90519.0],
       ['India', 35.0, 104113.0],
       ['India', 34.0, 48242.0],
       ['USA', 62.0, 111918.0],
       ['Brazil', 44.0, 71415.0],
       ['Brazil', 39.0, 77453.0],
       ['Brazil', 37.0, 80946.0],
       ['Brazil', 52.0, 116024.0],
       ['USA', 21.0, 37424.0],
       ['India', 35.0, 113092.0],
       ['India', 68.0, 105436.0]], dtype=object)

In [26]:
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()
X[: , 0] = le.fit_transform(X[: , 0])

In [29]:
X

array([[0, 38.0, 83572.0],
       [2, 26.0, 106573.0],
       [0, 42.425, 84411.45],
       [2, 20.0, 107675.0],
       [1, 42.425, 84411.45],
       [1, 42.425, 84411.45],
       [0, 42.425, 84411.45],
       [0, 21.0, 88417.0],
       [2, 41.0, 95610.0],
       [0, 30.0, 93070.0],
       [0, 42.425, 84411.45],
       [2, 42.0, 99195.0],
       [1, 26.0, 72067.0],
       [0, 57.0, 52503.0],
       [2, 38.0, 111125.0],
       [2, 68.0, 113726.0],
       [2, 54.0, 67414.0],
       [2, 27.0, 66479.0],
       [0, 46.0, 43105.0],
       [2, 42.425, 84411.45],
       [1, 42.425, 84411.45],
       [2, 58.0, 72774.0],
       [2, 25.0, 98620.0],
       [1, 30.0, 43624.0],
       [2, 42.425, 84411.45],
       [1, 36.0, 89203.0],
       [2, 42.425, 84411.45],
       [2, 58.0, 94680.0],
       [1, 68.0, 82844.0],
       [0, 58.0, 118065.0],
       [0, 56.0, 54920.0],
       [0, 49.0, 118342.0],
       [0, 39.0, 61169.0],
       [2, 63.0, 51535.0],
       [0, 69.0, 110862.0],
       [2, 42.425, 84411.45],
       [0, 24.0, 97735.0],
       [2, 19.0, 47869.0],
       [2, 58.0, 77103.0],
       [1, 26.0, 90519.0],
       [1, 35.0, 104113.0],
       [1, 34.0, 48242.0],
       [2, 62.0, 111918.0],
       [0, 44.0, 71415.0],
       [0, 39.0, 77453.0],
       [0, 37.0, 80946.0],
       [0, 52.0, 116024.0],
       [2, 21.0, 37424.0],
       [1, 35.0, 113092.0],
       [1, 68.0, 105436.0]], dtype=object)

In [30]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [33]:
ct = ColumnTransformer([('country' , OneHotEncoder() , [0])] , remainder='passthrough')
X = ct.fit_transform(X)
X

array([[0.0, 1.0, 0.0, 0.0, 38.0, 83572.0],
       [1.0, 0.0, 0.0, 1.0, 26.0, 106573.0],
       [0.0, 1.0, 0.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 0.0, 1.0, 20.0, 107675.0],
       [1.0, 0.0, 1.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 1.0, 0.0, 42.425, 84411.45],
       [0.0, 1.0, 0.0, 0.0, 42.425, 84411.45],
       [0.0, 1.0, 0.0, 0.0, 21.0, 88417.0],
       [1.0, 0.0, 0.0, 1.0, 41.0, 95610.0],
       [0.0, 1.0, 0.0, 0.0, 30.0, 93070.0],
       [0.0, 1.0, 0.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 0.0, 1.0, 42.0, 99195.0],
       [1.0, 0.0, 1.0, 0.0, 26.0, 72067.0],
       [0.0, 1.0, 0.0, 0.0, 57.0, 52503.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 111125.0],
       [1.0, 0.0, 0.0, 1.0, 68.0, 113726.0],
       [1.0, 0.0, 0.0, 1.0, 54.0, 67414.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 66479.0],
       [0.0, 1.0, 0.0, 0.0, 46.0, 43105.0],
       [1.0, 0.0, 0.0, 1.0, 42.425, 84411.45],
       [1.0, 0.0, 1.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 0.0, 1.0, 58.0, 72774.0],
       [1.0, 0.0, 0.0, 1.0, 25.0, 98620.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 43624.0],
       [1.0, 0.0, 0.0, 1.0, 42.425, 84411.45],
       [1.0, 0.0, 1.0, 0.0, 36.0, 89203.0],
       [1.0, 0.0, 0.0, 1.0, 42.425, 84411.45],
       [1.0, 0.0, 0.0, 1.0, 58.0, 94680.0],
       [1.0, 0.0, 1.0, 0.0, 68.0, 82844.0],
       [0.0, 1.0, 0.0, 0.0, 58.0, 118065.0],
       [0.0, 1.0, 0.0, 0.0, 56.0, 54920.0],
       [0.0, 1.0, 0.0, 0.0, 49.0, 118342.0],
       [0.0, 1.0, 0.0, 0.0, 39.0, 61169.0],
       [1.0, 0.0, 0.0, 1.0, 63.0, 51535.0],
       [0.0, 1.0, 0.0, 0.0, 69.0, 110862.0],
       [1.0, 0.0, 0.0, 1.0, 42.425, 84411.45],
       [0.0, 1.0, 0.0, 0.0, 24.0, 97735.0],
       [1.0, 0.0, 0.0, 1.0, 19.0, 47869.0],
       [1.0, 0.0, 0.0, 1.0, 58.0, 77103.0],
       [1.0, 0.0, 1.0, 0.0, 26.0, 90519.0],
       [1.0, 0.0, 1.0, 0.0, 35.0, 104113.0],
       [1.0, 0.0, 1.0, 0.0, 34.0, 48242.0],
       [1.0, 0.0, 0.0, 1.0, 62.0, 111918.0],
       [0.0, 1.0, 0.0, 0.0, 44.0, 71415.0],
       [0.0, 1.0, 0.0, 0.0, 39.0, 77453.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 80946.0],
       [0.0, 1.0, 0.0, 0.0, 52.0, 116024.0],
       [1.0, 0.0, 0.0, 1.0, 21.0, 37424.0],
       [1.0, 0.0, 1.0, 0.0, 35.0, 113092.0],
       [1.0, 0.0, 1.0, 0.0, 68.0, 105436.0]], dtype=object)

In [34]:
from sklearn.preprocessing import StandardScaler

In [36]:
ss = StandardScaler()
X = ss.fit_transform(X)

In [37]:
X

array([[-1.33333333,  1.33333333, -0.56195149, -0.81649658, -0.32252435,
        -0.03923179],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.19716666,
         1.03572262],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.        ,
         0.        ],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.63448781,
         1.08722472],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658,  0.        ,
         0.        ],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658,  0.        ,
         0.        ],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.        ,
         0.        ],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -1.56160095,
         0.18719985],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -0.10386377,
         0.52336554],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -0.90561922,
         0.40465834],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.        ,
         0.        ],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -0.03097692,
         0.69091093],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658, -1.19716666,
        -0.57691931],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  1.06232597,
        -1.49124513],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -0.32252435,
         1.24846087],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  1.86408141,
         1.37001891],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  0.84366539,
        -0.79437781],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.1242798 ,
        -0.83807514],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.26057052,
        -1.93046175],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  0.        ,
         0.        ],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658,  0.        ,
         0.        ],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  1.13521283,
        -0.54387758],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.27005352,
         0.66403824],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658, -0.90561922,
        -1.90620623],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  0.        ,
         0.        ],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658, -0.46829807,
         0.22393365],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  0.        ,
         0.        ],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  1.13521283,
         0.47990188],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658,  1.86408141,
        -0.07325496],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  1.13521283,
         1.57280258],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.98943911,
        -1.37828635],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.4792311 ,
         1.58574821],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -0.24963749,
        -1.08623861],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  1.49964712,
        -1.53648472],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  1.93696827,
         1.23616953],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  0.        ,
         0.        ],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -1.34294037,
         0.62267766],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.70737467,
        -1.70781566],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  1.13521283,
        -0.34156126],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658, -1.19716666,
         0.28543706],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658, -0.54118493,
         0.92075423],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658, -0.61407179,
        -1.69038346],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487,  1.42676026,
         1.28552182],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.1147968 ,
        -0.6073906 ],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -0.24963749,
        -0.32520397],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -0.39541121,
        -0.16195821],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.69789167,
         1.47741621],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.56160095,
        -2.19596395],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658, -0.54118493,
         1.34038884],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658,  1.86408141,
         0.98258479]])